services:
  - type: web
    name: green-tech-vault
    env: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://greentechuser:greentechpassword@cluster0.mongodb.net/green-tech-vault?retryWrites=true&w=majority
    healthCheckPath: /wakeup
    healthCheckTimeout: 60
    autoDeploy: true 